export type Decision = { heading:string; choices:[string,string,string][]; picks:[string,string][] };
export const commercialDecisions:Record<string,Decision> = {
 '/dashcam-voiture':{heading:'Quelle configuration pour vos trajets quotidiens ?',choices:[['Garder une trace sans encombrer','Un modèle compact à l’avant','Commencez par le format et l’accès aux vidéos, puis comparez la définition.'],['Documenter aussi ce qui arrive derrière','Un kit avant et arrière','Prévoyez le passage du câble et vérifiez la caméra arrière incluse.'],['Filmer après avoir quitté la voiture','Un système compatible parking','Choisissez aussi son alimentation : la caméra seule ne suffit pas.']],picks:[['dashcam-voiture-discrete-2k','Pour débuter avec un format compact 2K et une consultation par Wi-Fi.'],['dashcam-3k-voiture','Pour ajouter une caméra arrière incluse et le contexte GPS au trajet.']]},
 '/dashcam-voiture-4k':{heading:'La 4K : choisir le système, pas seulement la définition',choices:[['Privilégier le détail à l’avant','Caméra 4K et capteur documenté','L’arrière reste une option à vérifier selon le kit.'],['Obtenir deux points de vue','Avant 4K + caméra arrière','Comparez séparément la définition de chaque canal.'],['Revoir de longues séquences','Stockage et transfert adaptés','Intégrez la carte compatible au budget et vérifiez le transfert vers le téléphone.']],picks:[['dashcam-4k','Une base 4K avec capteur IMX678 ; l’équipement arrière et connecté dépend du kit.'],['dashcam-wifi-5ghz','Une configuration 4K avant et 1080p arrière avec transfert Wi-Fi documenté.']]},
 '/dashcam-avant-arriere':{heading:'Deux caméras : quel compromis choisir ?',choices:[['Limiter l’encombrement','Un double système sans grand écran','Consultez les séquences dans l’application compatible.'],['Privilégier les détails à l’avant','Un kit 3K ou 4K avant','Ne supposez pas la même définition pour la caméra arrière.'],['Installer sur une moto','Un kit spécifiquement conçu pour la moto','Montage extérieur, protection et alimentation diffèrent de ceux d’une voiture.']],picks:[['dashcam-avant-arriere','La N1 Dual privilégie les deux points de vue dans un format sans écran encombrant.'],['dashcam-3k-voiture','L’A510 associe une caméra avant 3K HDR à une caméra arrière incluse.']]},
 '/mode-parking':{heading:'Caméra + alimentation : votre choix en deux parties',choices:[['Une prise coupée avec le contact','Prévoir une alimentation compatible','Sans énergie à l’arrêt, la caméra ne peut pas surveiller le véhicule.'],['Une priorité aux incidents à l’arrêt','Vérifier le déclenchement du modèle','Choc, mouvement et time-lapse ne produisent pas le même enregistrement.'],['Des stationnements prolongés','Vérifier énergie et protection batterie','Ne comparez pas les durées annoncées sans examiner leurs conditions.']],picks:[['dashcam-3k-voiture','Mode parking documenté avec kit d’alimentation 70mai compatible non inclus.'],['dashcam-wifi-5ghz','Surveillance annoncée jusqu’à 48 h avec kit intelligent séparé : durée conditionnelle, pas autonomie garantie.']]},
 '/dashcam-moto':{heading:'Le bon montage avant le nombre de pixels',choices:[['Vous changez souvent de moto','Caméra portée sur le casque','Vérifiez support, recharge et compatibilité du casque.'],['Vous préférez un équipement qui reste en place','Kit fixe avant et arrière','Prévoyez montage, câblage et protection de chaque connexion.'],['Vous souhaitez aussi la navigation','Écran connecté avec DVR documenté','CarPlay seul ne signifie pas présence de caméras ni fonctionnement simultané.']],picks:[['camera-casque-moto-4k','La FX60C combine caméra 4K stabilisée et intercom de casque.'],['dashcam-moto-etanche','La VSYS privilégie un montage fixe double caméra ; choisissez les accessoires adaptés à la moto.']]},
 '/dashcam-vision-nocturne':{heading:'Filmer la route de nuit ou l’habitacle ?',choices:[['Une route sombre ou des phares contrastés','Capteur et traitement HDR / nocturne','Regardez les limites sur les scènes en mouvement, pas seulement une image fixe.'],['Un habitacle peu éclairé','Caméra intérieure avec infrarouge documenté','Les LED de l’habitacle ne prouvent pas la qualité de lecture à l’extérieur.'],['Une voiture garée la nuit','Traitement nocturne + alimentation parking','L’image et l’alimentation répondent à deux besoins distincts.']],picks:[['dashcam-4k','Pour comparer une caméra de route 4K avec capteur IMX678 et HDR.'],['dashcam-voiture-vision-nocturne','Pour examiner une configuration avec habitacle et infrarouge : vérifier impérativement la variante 2CH ou 3CH.']]},
 '/dashcam-gps':{heading:'Ce que le GPS ajoute — et ce qu’il ne remplace pas',choices:[['Contextualiser le trajet','Position et données documentées','Vérifiez les informations effectivement enregistrées et leur consultation.'],['Exporter une séquence sur téléphone','Application et connexion compatibles','Le GPS ne réalise pas le transfert : comparez aussi le Wi-Fi.'],['Retrouver un véhicule à distance','Service connecté distinct','Un GPS seul ne suffit pas à communiquer la position sur internet.']],picks:[['dashcam-3k-voiture','GPS intégré avec vitesse et position enregistrées selon la fiche, plus caméra arrière incluse.'],['dashcam-wifi-5ghz','GPS intégré et double enregistrement, avec consultation via l’application compatible.']]},
 '/meilleure-dashcam':{heading:'Notre sélection par priorité, sans vainqueur artificiel',choices:[['Discrétion au quotidien','Une caméra compacte 2K','Payez pour la couverture et les fonctions que vous utiliserez réellement.'],['Contexte avant et arrière','Un kit double caméra','Comparez l’image de chaque canal et le coût de l’installation.'],['Sorties à moto','Casque ou kit fixe','Le montage et l’alimentation passent avant un classement par résolution.']],picks:[['dashcam-voiture-discrete-2k','Pour la discrétion et les trajets quotidiens : 2K, Wi-Fi et format compact.'],['dashcam-3k-voiture','Pour une couverture voiture avant arrière avec image avant 3K et GPS.']]},
};
