export type CommercialPage = { title: string; description: string; intro: string; criteria: [string,string][]; faq: [string,string][]; guide: string; guideLabel: string };
export const commercialPages: Record<string,CommercialPage> = {
 '/dashcam-voiture': {
 title:'Dashcam voiture : choisir et comparer les modèles | NORTICAM',
 description:'Trouvez une dashcam voiture adaptée : format discret, 2K ou 4K, caméra arrière et mode parking. Comparez les configurations et les prix NORTICAM.',
 intro:'Une dashcam voiture enregistre vos trajets pour conserver le contexte d’un incident. Commencez par les angles à filmer, puis choisissez le niveau de détail et l’installation qui vous conviennent. Nos modèles ci-dessous permettent de comparer ces compromis sans multiplier les équipements.',
 criteria:[['Une ou deux caméras ?','L’avant couvre la route. Une caméra arrière ajoute le contexte derrière le véhicule et demande un passage de câble supplémentaire. Vérifiez qu’elle figure bien dans le kit choisi.'],['Définition et discrétion','Un format compact est utile derrière le rétroviseur. La 2K ou la 4K décrit la définition, mais le capteur, la lumière et les reflets comptent aussi.'],['Prévoir le coût complet','Ajoutez au budget la carte mémoire et, si nécessaire, le kit d’alimentation pour le stationnement. Leur présence varie selon la configuration.']],
 faq:[['Une dashcam filme-t-elle quand le moteur est arrêté ?','Seulement si le modèle et son alimentation permettent le mode parking. Une prise coupée avec le contact ne fournit plus d’énergie à la caméra.'],['Le Wi-Fi remplace-t-il une connexion mobile ?','Le Wi-Fi sert généralement à relier le téléphone à proximité de la caméra. Il ne signifie pas qu’une consultation à distance par internet est disponible.'],['La 4K garantit-elle une plaque lisible ?','Non. La distance, le mouvement, la météo, les reflets et l’exposition peuvent limiter la lisibilité, quelle que soit la définition.']],
 guide:'/conseils/quelle-dashcam-voiture-choisir',guideLabel:'Lire le guide de choix voiture'},
 '/dashcam-moto': {
 title:'Dashcam moto : caméra de casque ou kit fixe | NORTICAM',
 description:'Comparez les dashcams moto : casque, kit avant arrière et écran connecté. Vérifiez montage, alimentation et configuration avant achat.',
 intro:'À moto, le montage compte autant que l’image. Une caméra de casque suit le regard du pilote ; un kit fixe filme depuis la moto. Choisissez d’abord cette configuration, puis vérifiez l’alimentation, les supports et la résistance à l’eau annoncée pour chaque élément.',
 criteria:[['Casque ou montage fixe','La caméra de casque suit le pilote et peut demander une recharge. Un kit fixe reste sur la moto et nécessite une installation adaptée.'],['Lire le contenu du kit','Un écran connecté n’inclut pas nécessairement deux caméras. Consultez l’intitulé de la variante et les composants fournis.'],['Vérifier les conditions d’usage','L’indice de protection, le montage, le câblage et les connexions doivent correspondre aux conditions de votre trajet. Ne déduisez pas la résistance de tout le kit de celle d’un seul composant.']],
 faq:[['Une caméra rotative filme-t-elle à 360° simultanément ?','Pas nécessairement. Un objectif orientable permet de changer de direction ; ce n’est pas la même chose qu’une capture panoramique simultanée.'],['CarPlay inclut-il automatiquement l’enregistrement ?','Non. CarPlay et le DVR sont des fonctions différentes. Vérifiez la présence des caméras et les éventuelles limites d’utilisation simultanée.'],['Une caméra de casque convient-elle à tous les casques ?','Vérifiez les supports compatibles et les recommandations du fabricant du casque avant toute fixation.']],
 guide:'/conseils/dashcam-moto-guide',guideLabel:'Préparer votre équipement moto'},
 '/dashcam-voiture-4k': {
 title:'Dashcam 4K voiture : comparer image et configurations | NORTICAM',
 description:'Choisissez une dashcam 4K selon votre usage : couverture, vision nocturne, stockage et budget. Consultez les prix et variantes du catalogue NORTICAM.',
 intro:'La 4K donne davantage de pixels pour examiner une scène ou recadrer une vidéo. Elle est pertinente si le détail est votre priorité, à condition de considérer aussi le capteur, le traitement nocturne et la carte mémoire. Comparez la définition de chaque caméra : une façade 4K ne signifie pas forcément une caméra arrière 4K.',
 criteria:[['Avant et arrière séparément','Vérifiez les résolutions annoncées pour chaque canal. Le mode double enregistrement peut avoir ses propres réglages.'],['Stockage adapté','Une définition élevée peut produire des fichiers plus volumineux. Respectez la capacité et la classe de carte mémoire indiquées par le fabricant.'],['Comparer en conditions réelles','Pour la nuit, regardez la lisibilité des éléments en mouvement. Un exemple de jour ne prouve pas la même performance sous la pluie ou dans une rue sombre.']],
 faq:[['La 4K est-elle toujours préférable à la 2K ?','Pas pour tous les usages. Une 2K compacte peut mieux correspondre à votre budget ou à votre priorité de discrétion. Comparez le système complet.'],['Toutes les cartes microSD conviennent-elles ?','Non. Capacité, vitesse et endurance doivent correspondre aux recommandations du modèle.'],['Une caméra arrière est-elle incluse ?','Cela dépend du kit. Vérifiez la variante avant d’ajouter le modèle au panier.']],
 guide:'/conseils/dashcam-2k-vs-4k',guideLabel:'Comprendre les différences entre 2K et 4K'},
 '/dashcam-avant-arriere': {
 title:'Dashcam avant arrière : comparer les kits double caméra | NORTICAM',
 description:'Filmez devant et derrière votre véhicule. Comparez les dashcams avant arrière, leurs résolutions, leurs kits et leurs conditions de montage.',
 intro:'Une dashcam avant arrière conserve deux points de vue d’un même trajet. C’est une configuration utile pour documenter ce qui arrive derrière le véhicule, en complément de la route. Les modèles ci-dessous décrivent une couverture double dans leur catalogue : vérifiez toujours la variante et les accessoires du kit.',
 criteria:[['Deux angles cohérents','Comparez la définition de l’avant et de l’arrière, ainsi que les options du kit. Le nombre de canaux ne suffit pas à décrire l’image obtenue.'],['Anticiper le passage du câble','La caméra arrière demande un cheminement jusqu’à la vitre ou au point de montage prévu. La longueur et les passages du hayon méritent d’être vérifiés.'],['Stationnement : une fonction distincte','Deux caméras ne garantissent pas l’enregistrement moteur coupé. Le mode parking et son alimentation restent à confirmer séparément.']],
 faq:[['Pourquoi filmer l’arrière ?','Pour conserver le contexte derrière le véhicule, qu’une caméra avant ne peut pas montrer.'],['Une caméra arrière peut-elle se monter à l’extérieur ?','Uniquement si le modèle et son indice de protection le permettent. Une caméra pour vitre intérieure ne doit pas être assimilée à une caméra extérieure.'],['Le kit comprend-il tous les accessoires ?','L’intitulé de variante et la fiche donnent le contenu documenté. Demandez confirmation pour tout composant non précisé.']],
 guide:'/conseils/dashcam-avant-arriere-guide',guideLabel:'Comprendre le double enregistrement'},
 '/mode-parking': {
 title:'Dashcam mode parking : surveiller une voiture garée | NORTICAM',
 description:'Comparez les dashcams avec mode parking : alimentation, kit compatible, détection et stockage. Préparez votre équipement pour une voiture garée.',
 intro:'Pour une voiture garée, la caméra doit pouvoir rester alimentée et disposer d’un mode adapté. Le mode parking peut fonctionner par détection, intervalles ou selon une autre logique propre au modèle. Choisissez la caméra et son alimentation ensemble : une fonction annoncée ne signifie pas que le kit nécessaire est inclus.',
 criteria:[['La bonne alimentation','Une alimentation permanente compatible ou une solution dédiée peut être nécessaire. Vérifiez les protections prévues et faites installer le kit si besoin.'],['Comprendre ce qui déclenche une séquence','Détection de choc, mouvement et time-lapse ne rendent pas le même service. Consultez la documentation du modèle pour connaître son fonctionnement exact.'],['Autonomie et durée','La durée dépend de l’alimentation, des réglages et de l’environnement. Une mention 24 h ou 48 h ne garantit pas cette durée dans toutes les situations.']],
 faq:[['Le mode parking fonctionne-t-il sur l’allume-cigare ?','Il dépend du maintien de l’alimentation à l’arrêt et des exigences de la caméra. Ne supposez pas que toutes les prises restent actives.'],['La voiture est-elle surveillée sans limite de durée ?','Non. L’énergie disponible et les réglages limitent la durée ; vérifiez la protection contre une décharge excessive.'],['Le kit parking est-il fourni ?','Consultez la variante : plusieurs modèles nécessitent un kit compatible vendu séparément.']],
 guide:'/conseils/dashcam-mode-parking-guide',guideLabel:'Équiper une voiture garée'},
 '/dashcam-vision-nocturne': {
 title:'Dashcam vision nocturne : choisir pour les trajets de nuit | NORTICAM',
 description:'Comparez les dashcams pour la nuit : capteur, HDR, traitement de l’image et alimentation. Trouvez la configuration adaptée à vos trajets.',
 intro:'Pour rouler de nuit, regardez au-delà de la définition. Le capteur et le traitement d’image influencent la scène enregistrée lorsque l’éclairage change. La sélection rassemble les modèles dont le catalogue décrit un traitement nocturne ou HDR ; elle ne constitue pas un classement fondé sur des essais comparatifs.',
 criteria:[['Lumière et mouvement','Une image à l’arrêt dans une rue éclairée ne reflète pas nécessairement un croisement rapide sur une route sombre. Cherchez des séquences représentatives de vos trajets.'],['Comprendre le HDR','Le HDR cherche à mieux gérer les écarts de luminosité. Il ne garantit pas la lecture d’une plaque en toute situation.'],['Préserver la qualité réelle','Un pare-brise propre, un bon positionnement et la maîtrise des reflets comptent aussi. Suivez les réglages conseillés pour le modèle.']],
 faq:[['Vision nocturne signifie-t-elle infrarouge ?','Non. Le terme peut désigner un capteur ou un traitement d’image. La présence d’infrarouge doit être explicitement indiquée.'],['Peut-on identifier toutes les plaques la nuit ?','Non. Le mouvement, la distance, les phares et la météo peuvent empêcher leur lecture.'],['La 4K suffit-elle pour choisir ?','Non. Comparez les informations sur le capteur, le HDR et les conditions des vidéos de démonstration quand elles existent.']],
 guide:'/conseils/dashcam-nuit',guideLabel:'Les critères utiles pour filmer la nuit'},
 '/dashcam-gps': {
 title:'Dashcam GPS : comparer localisation et vidéo | NORTICAM',
 description:'Découvrez les dashcams dont le catalogue mentionne le GPS. Comparez couverture, résolution, variantes et fonctions avant votre achat.',
 intro:'Sur une dashcam, le GPS peut compléter la vidéo par des informations de position ou de vitesse. Il ne faut pas le confondre avec une connexion mobile ou un suivi à distance. Vérifiez si le GPS est intégré, optionnel ou dépendant de la variante avant de choisir.',
 criteria:[['Intégré ou selon variante','Une même famille de produits peut proposer plusieurs équipements. Lisez la description précise du GPS dans la fiche.'],['Consultation des données','Vérifiez comment les données sont affichées ou exportées dans l’application du fabricant. Les possibilités varient selon le modèle.'],['Rester centré sur la caméra','Le GPS ne remplace ni une bonne couverture vidéo ni une installation adaptée. Comparez aussi la définition et l’alimentation.']],
 faq:[['Le GPS permet-il de retrouver une voiture à distance ?','Pas à lui seul. Il faut une fonction de communication et un service compatibles explicitement proposés.'],['GPS et Wi-Fi sont-ils équivalents ?','Non. Le GPS sert à la localisation ; le Wi-Fi relie généralement la caméra au téléphone à proximité.'],['Tous les kits du modèle comprennent-ils le GPS ?','Pas nécessairement. Vérifiez la configuration choisie et demandez confirmation si la fiche indique “selon variante”.']],
 guide:'/conseils/quelle-dashcam-voiture-choisir',guideLabel:'Choisir les fonctions vraiment utiles'},
 '/meilleure-dashcam': {
 title:'Meilleure dashcam 2026 : notre sélection par usage | NORTICAM',
 description:'Quelle dashcam choisir en 2026 ? Comparez la sélection NORTICAM selon votre budget, la couverture, la nuit et le mode parking, sans classement artificiel.',
 intro:'La meilleure dashcam est celle qui correspond à votre véhicule et à vos priorités. Notre sélection 2026 organise les modèles du catalogue par usage, avec leurs prix actuels et les points à vérifier. Il s’agit d’une aide au choix éditoriale, pas d’un palmarès de tests en laboratoire ni d’un classement de ventes.',
 criteria:[['Petit budget ou équipement complet','Comparez le coût du modèle et celui des éléments indispensables, notamment la carte mémoire et l’alimentation parking.'],['Choisir un critère principal','Pour plus de contexte : avant et arrière. Pour examiner le détail : définition et capteur. Pour la voiture garée : mode parking et alimentation.'],['Vérifier les compromis','Un écran, une caméra supplémentaire ou une fonction connectée peut modifier l’encombrement et l’installation. Choisissez ce que vous utiliserez réellement.']],
 faq:[['Existe-t-il une meilleure dashcam pour tout le monde ?','Non. Le véhicule, le budget, l’installation et les angles à filmer changent le choix pertinent.'],['Ce classement est-il basé sur des avis clients ?','Non. Cette sélection s’appuie sur les caractéristiques du catalogue. Aucun avis ni volume de ventes n’est utilisé sans données vérifiables.'],['Comment départager deux modèles ?','Ouvrez le comparateur pour lire les différences, puis vérifiez la variante et le contenu du kit sur chaque fiche.']],
 guide:'/quiz',guideLabel:'Obtenir une recommandation personnalisée'},
};
