import type { StoreProduct } from './shopify';
import { productFacts } from './product-facts';

export type CommercialPage = { title: string; description: string; intro: string; criteria: [string,string][]; faq: [string,string][]; guide: string; guideLabel: string; related?: [string,string,string][] };

/** Explicitly connect each broad vehicle selection to its specialist buying intent. */
export const contextualCollectionLinks: Record<string, { copy: string; href: string; label: string }> = {
 '/dashcam-voiture': { copy:'Vous recherchez un objectif qui peut changer de direction, plutôt que des caméras fixes ?', href:'/dashcam-voiture-360', label:'Comprendre et choisir une dashcam voiture 360°' },
 '/dashcam-moto': { copy:'Vous souhaitez afficher la navigation du téléphone sur le guidon, en plus de comparer les caméras ?', href:'/ecran-moto-carplay', label:'Comparer les écrans moto CarPlay et leurs kits DVR' },
};

/** A title mentioning a function does not override an explicit negative in the live catalogue. */
export function specialtyCollectionProducts(route: string, products: StoreProduct[]): StoreProduct[] | undefined {
 if (route !== '/dashcam-voiture-360' && route !== '/ecran-moto-carplay') return undefined;
 return products.filter(product => {
  const vehicle = productFacts(product).vehicle;
  const description = `${product.title} ${product.description} ${product.details.join(' ')}`;
  if (route === '/dashcam-voiture-360') {
   const describedRotation = /\b(?:caméra|objectif)[^.!?]{0,45}(?:rotatif|rotative|orientable|motorisé)[^.!?]{0,25}\b360(?:°|\b)/i.test(product.description);
   const rotation = product.specs ? product.specs.capabilities?.rotation === true && /\b360(?:°|\b)/i.test(`${product.specs.facts?.rotation || ''} ${product.title}`) : (/\b360(?:°|\b)/i.test(`${product.title} ${product.details.join(' ')}`) || describedRotation) && !/(?:sans|pas de|non)\s+(?:rotation\s+)?360|360[^.!?]{0,25}(?:non disponible|non prise? en charge)/i.test(description);
   return vehicle === 'voiture' && rotation;
  }
  const describedCarplay = /\b(?:avec|compatible avec|intègre|prend en charge)\s+(?:Apple\s+)?CarPlay\b|\bCarPlay\s+(?:sans fil|et Android Auto|intégré)/i.test(product.description);
  const carplay = product.specs ? product.specs.capabilities?.carplay === true : (/\bCarPlay\b/i.test(`${product.title} ${product.details.join(' ')}`) || describedCarplay) && !/(?:sans|pas de|non compatible avec)\s+CarPlay|CarPlay[^.!?]{0,25}(?:non disponible|non prise? en charge|non compatible)/i.test(description);
  return vehicle === 'moto' && carplay;
 });
}

export const commercialPages: Record<string,CommercialPage> = {
 '/dashcam-voiture-360': {
 title:'Dashcam voiture 360° : caméra rotative et choix du kit | NORTICAM',
 description:'Comparez une dashcam voiture 360° rotative : angles filmés, kit, alimentation parking et limites. Découvrez la 70mai X800 Omni et ses configurations.',
 intro:'Une dashcam voiture 360° rotative permet d’orienter l’objectif vers différentes directions. Elle ne filme pas nécessairement tout autour du véhicule simultanément. Comparez le modèle disponible ci-dessous, puis vérifiez le nombre de caméras, le contenu du kit et l’alimentation adaptée à votre usage.',
 criteria:[['Rotation ou enregistrement panoramique ?','L’angle de rotation décrit le mouvement de l’objectif, pas forcément le champ enregistré à chaque instant. Une caméra orientée sur le côté ne montre pas automatiquement l’avant et l’arrière en même temps. Vérifiez comment la direction est réglée, les modes disponibles et les conditions de déclenchement dans la documentation du modèle.'],['Choisir les caméras du kit','La famille 70mai X800 Omni propose plusieurs configurations. Une caméra supplémentaire, une carte mémoire ou un kit d’alimentation ne doivent pas être déduits du nom du produit. Consultez les options de la fiche et le contenu documenté de la variante. Si vous voulez deux points de vue fixes pendant le trajet, comparez aussi les kits avant et arrière.'],['Préparer le montage et le stationnement','Prévoyez un emplacement qui laisse l’objectif s’orienter sans gêner la visibilité. Vitres, montants et reflets peuvent masquer une partie de la scène. Pour une voiture garée, vérifiez séparément le mode parking et l’alimentation compatible : la rotation seule n’apporte ni énergie moteur coupé, ni accès à distance.']],
 faq:[['Une dashcam 360° filme-t-elle tous les côtés en même temps ?','Pas nécessairement. Une caméra rotative change de direction ; une capture panoramique simultanée fonctionne autrement. Choisissez selon les angles réellement enregistrés dans le mode que vous utiliserez, et non selon la seule mention 360°.'],['Faut-il choisir une caméra rotative ou un kit avant arrière ?','Une caméra rotative est à envisager si vous souhaitez pouvoir changer de point de vue. Un kit à deux caméras fixes est une autre piste si votre priorité est de conserver la route devant et derrière. Vérifiez les canaux de la configuration choisie ; aucune de ces solutions ne garantit une absence totale d’angle mort.'],['Quel modèle 360° propose NORTICAM ?','La sélection ci-dessus présente les modèles voiture dont le catalogue décrit une fonction 360°, notamment la 70mai X800 Omni. La fiche donne les variantes, leurs prix actuels et les accessoires documentés. Ce n’est pas un classement fondé sur des tests de toute la gamme.'],['Peut-on filmer la voiture garée avec la X800 Omni ?','Le catalogue décrit un mode de stationnement avec une alimentation compatible. Vérifiez le kit nécessaire, sa présence dans la variante et les consignes de montage. La durée dépend de l’énergie disponible et des réglages ; ne supposez pas une surveillance illimitée.'],['La rotation 360° permet-elle de consulter la caméra à distance ?','Non, pas à elle seule. Une consultation par internet demande une fonction de communication et un service compatibles explicitement prévus. Le Wi-Fi local et le GPS ne doivent pas être interprétés comme une connexion mobile ou une option 4G incluse.']],
 guide:'/conseils/dashcam-avant-arriere-guide',guideLabel:'Comprendre l’alternative avant et arrière',
 related:[['/dashcam-avant-arriere','Comparer les kits avant et arrière','Pour conserver deux directions fixes pendant vos trajets.'],['/mode-parking','Choisir pour une voiture garée','Pour examiner le déclenchement et l’alimentation à l’arrêt.'],['/conseils/quelle-dashcam-voiture-choisir','Préparer votre choix voiture','Pour hiérarchiser couverture, montage et budget.']]},
 '/ecran-moto-carplay': {
 title:'Écran moto CarPlay : navigation, DVR et choix du kit | NORTICAM',
 description:'Comparez les écrans moto CarPlay : taille, smartphone, alimentation, caméras et limites du DVR. Vérifiez les kits Jansite et JMCQ avant de choisir.',
 intro:'Un écran moto CarPlay affiche les fonctions compatibles du téléphone sur le guidon. Certains kits ajoutent des caméras, mais CarPlay ne signifie pas automatiquement enregistrement vidéo. Comparez les écrans disponibles ci-dessous, puis vérifiez le téléphone, le montage et les conditions d’utilisation du DVR de chaque configuration.',
 criteria:[['Téléphone et casque compatibles','Vérifiez la version de votre téléphone, les fonctions CarPlay ou Android Auto documentées et les connexions prévues avec le casque. Ces systèmes ne prennent pas en charge toutes les applications ni tous les appareils. Une liaison Bluetooth avec un casque ne doit pas être confondue avec un intercom entre plusieurs motards. Préparez la navigation et les réglages à l’arrêt.'],['La place disponible sur le guidon','Comparez la taille de l’écran avec l’espace réellement libre, la position de conduite et les commandes de la moto. Un écran plus large n’est pas automatiquement le meilleur choix : il doit rester lisible sans masquer les informations utiles ni gêner les mouvements. Vérifiez le support, le raccordement électrique et la protection annoncée pour chaque composant.'],['DVR, caméras et carte mémoire','L’écran, l’enregistreur et les caméras sont des éléments distincts. Vérifiez quelles caméras sont incluses, leur résolution et la carte compatible. Le catalogue du JMCQ DVR précise un enregistrement hors mode CarPlay : ne le choisissez pas en supposant ces deux modes simultanés. Pour tout autre modèle, demandez confirmation si cette utilisation n’est pas documentée.']],
 faq:[['CarPlay inclut-il une dashcam ?','Non. CarPlay sert à retrouver certaines fonctions du téléphone sur l’écran. Le DVR assure l’enregistrement vidéo lorsqu’il est présent. La variante doit préciser les caméras et les accessoires inclus ; la présence d’un écran ne suffit pas.'],['Peut-on utiliser CarPlay et filmer en même temps ?','Cela dépend du modèle et du mode choisi. Pour le JMCQ DVR du catalogue, l’enregistrement s’utilise hors mode CarPlay. Pour le Jansite, vérifiez la documentation de la configuration avant de compter sur les deux fonctions simultanément.'],['Ces écrans fonctionnent-ils avec tous les smartphones ?','Non, nous ne promettons pas une compatibilité universelle. Vérifiez le système du téléphone, sa version et les conditions CarPlay ou Android Auto du modèle exact. Consultez aussi les consignes de liaison avec votre casque Bluetooth.'],['Quelle différence entre le Jansite 8,1 pouces et le JMCQ DVR ?','Le catalogue décrit le Jansite avec un écran 8,1 pouces et une caméra avant 4K, l’arrière dépendant de la configuration. Le JMCQ propose un écran 6,86 pouces et un DVR double caméra avec une limite hors mode CarPlay. Comparez ensuite le kit, la place sur le guidon et le prix affiché sur chaque fiche.'],['Comment alimenter et installer un écran moto ?','Suivez le faisceau et les consignes du fabricant pour le modèle et la moto. Le catalogue du JMCQ impose le faisceau ACC fourni ; ce n’est pas une règle à transposer automatiquement aux autres écrans. Si vous ne maîtrisez pas le raccordement et le montage, faites appel à une personne compétente.']],
 guide:'/conseils/dashcam-moto-guide',guideLabel:'Préparer le montage de votre équipement moto',
 related:[['/dashcam-moto','Comparer tous les montages moto','Pour choisir entre caméra de casque, kit fixe et écran connecté.'],['/dashcam-moto-casque','Voir les caméras de casque','Si votre priorité est le point de vue du pilote, plutôt qu’un écran sur le guidon.'],['/comparatif','Comparer les caractéristiques documentées','Pour lire la couverture, l’alimentation et les limites des modèles côte à côte.']]},
 '/dashcam-moto-casque': {
 title:'Caméra casque moto : comparer vidéo et intercom | NORTICAM',
 description:'Choisissez une caméra de casque moto : vidéo, intercom, fixation, recharge et stockage. Comparez les modèles et leurs configurations disponibles.',
 intro:'Une caméra de casque moto enregistre dans la direction de votre tête : elle suit votre regard pendant le trajet. Cette sélection réunit les équipements portés sur le casque, dont certains associent caméra et intercom. Pour choisir, comparez la définition vidéo, les communications dont vous avez besoin et surtout le montage compatible avec votre casque. Les prix ci-dessous correspondent aux configurations disponibles.',
 criteria:[['Fixation et confort sur votre casque','Avant de commander, identifiez la zone de fixation autorisée par le fabricant du casque et le type de support fourni. Vérifiez que l’équipement ne gêne ni la visière, ni les commandes, ni les mouvements de tête. Ne percez pas la coque. Le poids et la position de l’appareil comptent sur un long trajet autant que la définition vidéo.'],['Caméra seule ou caméra avec intercom','L’intercom permet de communiquer ; la caméra sert à enregistrer. Ce sont deux fonctions à comparer séparément : définition et stabilisation d’un côté, appareils compatibles et communications de l’autre. Vérifiez dans la notice les conditions de fonctionnement simultané, plutôt que de déduire les possibilités du seul nom du produit.'],['Recharge, stockage et récupération des vidéos','Une caméra portée sur le casque doit être préparée avant le départ : charge, espace disponible et orientation. La durée d’enregistrement varie avec les réglages et les fonctions utilisées. Vérifiez la carte mémoire compatible et si elle est incluse dans la configuration choisie. Faites un court essai à l’arrêt pour contrôler le cadrage et apprendre à récupérer une séquence.']],
 faq:[['Caméra de casque ou dashcam fixée sur la moto : quelle différence ?','La caméra de casque suit les mouvements de tête, ce qui permet de conserver le point de vue du pilote mais modifie le cadrage quand il regarde de côté. Une caméra fixée sur la moto conserve un angle lié au véhicule. Pour enregistrer l’avant et l’arrière depuis la moto, consultez plutôt notre sélection générale de dashcams moto.'],['Quel modèle choisir entre la FX60C et la R1 Plus ?','La FX60C est une piste si vous privilégiez la vidéo 4K stabilisée avec intercom. La R1 Plus associe une vidéo 1080p à un intercom. Notre comparatif détaille ces deux orientations ; vérifiez ensuite le kit, les fonctions et le prix de la configuration sur la fiche produit.'],['Une caméra de casque surveille-t-elle la moto une fois garée ?','Ne comptez pas sur un appareil emporté avec votre casque pour surveiller la moto laissée sur place. La surveillance du stationnement exige un équipement et une alimentation prévus pour cet usage ; ce n’est pas une fonction à supposer sur une caméra de casque.'],['Peut-on filmer toute une journée sans recharger ?','Cela dépend du modèle, de sa batterie et des fonctions activées. Nous ne promettons pas une autonomie identique pour tous les usages. Vérifiez la durée annoncée dans la documentation et prévoyez les recharges adaptées à vos sorties.'],['Est-ce une caméra panoramique à 360° ?','Un objectif orientable ne signifie pas que tous les angles sont enregistrés simultanément. Pour un produit présenté comme rotatif, vérifiez s’il s’agit du réglage de l’orientation ou d’une véritable capture panoramique.']],
 guide:'/comparatif/freedconn-r1-plus-vs-fodsports-fx60c',guideLabel:'Comparer la FreedConn R1 Plus et la Fodsports FX60C'},
 '/dashcam-voiture': {
 title:'Dashcam voiture : choisir et comparer les modèles | NORTICAM',
 description:'Trouvez une dashcam voiture adaptée : format discret, 2K ou 4K, caméra arrière et mode parking. Comparez les configurations et les prix NORTICAM.',
 intro:'Une dashcam voiture enregistre vos trajets pour conserver le contexte d’un incident. Commencez par les angles à filmer, puis choisissez le niveau de détail et l’installation qui vous conviennent. Nos modèles ci-dessous permettent de comparer ces compromis sans multiplier les équipements.',
 criteria:[['Une ou deux caméras ?','L’avant couvre la route. Une caméra arrière ajoute le contexte derrière le véhicule et demande un passage de câble supplémentaire. Vérifiez qu’elle figure bien dans le kit choisi.'],['Définition et discrétion','Un format compact est utile derrière le rétroviseur. La 2K ou la 4K décrit la définition, mais le capteur, la lumière et les reflets comptent aussi.'],['Prévoir le coût complet','Ajoutez au budget la carte mémoire et, si nécessaire, le kit d’alimentation pour le stationnement. Leur présence varie selon la configuration.']],
 faq:[['Une dashcam filme-t-elle quand le moteur est arrêté ?','Seulement si le modèle et son alimentation permettent le mode parking. Une prise coupée avec le contact ne fournit plus d’énergie à la caméra.'],['Le Wi-Fi remplace-t-il une connexion mobile ?','Le Wi-Fi sert généralement à relier le téléphone à proximité de la caméra. Il ne signifie pas qu’une consultation à distance par internet est disponible.'],['La 4K garantit-elle une plaque lisible ?','Non. La distance, le mouvement, la météo, les reflets et l’exposition peuvent limiter la lisibilité, quelle que soit la définition.']],
 guide:'/conseils/quelle-dashcam-voiture-choisir',guideLabel:'Lire le guide de choix voiture'},
 '/dashcam-moto': {
 title:'Dashcam moto : caméra de casque ou kit fixe | NORTICAM',
 description:'Comparez les dashcams moto : casque, kit avant arrière et écran connecté. Vérifiez montage, alimentation et configuration avant achat.',
 intro:'À moto, le montage compte autant que l’image. Une caméra de casque suit le regard du pilote ; un kit fixe filme depuis la moto. Choisissez d’abord cette configuration, puis vérifiez l’alimentation, les supports et la résistance à l’eau annoncée pour chaque élément.',
 criteria:[['Casque ou montage fixe','La caméra de casque suit le pilote et peut demander une recharge. Un kit fixe reste sur la moto et nécessite une installation adaptée.'],['Lire le contenu du kit','Un écran connecté n’inclut pas nécessairement deux caméras. Consultez l’intitulé de la variante et les composants fournis.'],['Vérifier les conditions d’usage','L’indice de protection, le montage, le câblage et les connexions doivent correspondre aux conditions de votre trajet. Ne déduisez pas la résistance de tout le kit de celle d’un seul composant.']],
 faq:[['Une caméra rotative filme-t-elle à 360° simultanément ?','Pas nécessairement. Un objectif orientable permet de changer de direction ; ce n’est pas la même chose qu’une capture panoramique simultanée.'],['CarPlay inclut-il automatiquement l’enregistrement ?','Non. CarPlay et le DVR sont des fonctions différentes. Vérifiez la présence des caméras et les éventuelles limites d’utilisation simultanée.'],['Une caméra de casque convient-elle à tous les casques ?','Vérifiez les supports compatibles et les recommandations du fabricant du casque avant toute fixation.']],
 guide:'/conseils/dashcam-moto-guide',guideLabel:'Préparer votre équipement moto'},
 '/dashcam-voiture-4k': {
 title:'Dashcam 4K voiture : comparer image et configurations | NORTICAM',
 description:'Choisissez une dashcam 4K selon votre usage : couverture, vision nocturne, stockage et budget. Consultez les prix et variantes du catalogue NORTICAM.',
 intro:'La 4K donne davantage de pixels pour examiner une scène ou recadrer une vidéo. Elle est pertinente si le détail est votre priorité, à condition de considérer aussi le capteur, le traitement nocturne et la carte mémoire. Comparez la définition de chaque caméra : une façade 4K ne signifie pas forcément une caméra arrière 4K.',
 criteria:[['Avant et arrière séparément','Vérifiez les résolutions annoncées pour chaque canal. Le mode double enregistrement peut avoir ses propres réglages.'],['Stockage adapté','Une définition élevée peut produire des fichiers plus volumineux. Respectez la capacité et la classe de carte mémoire indiquées par le fabricant.'],['Comparer en conditions réelles','Pour la nuit, regardez la lisibilité des éléments en mouvement. Un exemple de jour ne prouve pas la même performance sous la pluie ou dans une rue sombre.']],
 faq:[['La 4K est-elle toujours préférable à la 2K ?','Pas pour tous les usages. Une 2K compacte peut mieux correspondre à votre budget ou à votre priorité de discrétion. Comparez le système complet.'],['Toutes les cartes microSD conviennent-elles ?','Non. Capacité, vitesse et endurance doivent correspondre aux recommandations du modèle.'],['Une caméra arrière est-elle incluse ?','Cela dépend du kit. Vérifiez la variante avant d’ajouter le modèle au panier.']],
 guide:'/conseils/dashcam-2k-vs-4k',guideLabel:'Comprendre les différences entre 2K et 4K'},
 '/dashcam-avant-arriere': {
 title:'Dashcam avant arrière : comparer les kits double caméra | NORTICAM',
 description:'Filmez devant et derrière votre véhicule. Comparez les dashcams avant arrière, leurs résolutions, leurs kits et leurs conditions de montage.',
 intro:'Une dashcam avant arrière conserve deux points de vue d’un même trajet. C’est une configuration utile pour documenter ce qui arrive derrière le véhicule, en complément de la route. Les modèles ci-dessous décrivent une couverture double dans leur catalogue : vérifiez toujours la variante et les accessoires du kit.',
 criteria:[['Deux angles cohérents','Comparez la définition de l’avant et de l’arrière, ainsi que les options du kit. Le nombre de canaux ne suffit pas à décrire l’image obtenue.'],['Anticiper le passage du câble','La caméra arrière demande un cheminement jusqu’à la vitre ou au point de montage prévu. La longueur et les passages du hayon méritent d’être vérifiés.'],['Stationnement : une fonction distincte','Deux caméras ne garantissent pas l’enregistrement moteur coupé. Le mode parking et son alimentation restent à confirmer séparément.']],
 faq:[['Pourquoi filmer l’arrière ?','Pour conserver le contexte derrière le véhicule, qu’une caméra avant ne peut pas montrer.'],['Une caméra arrière peut-elle se monter à l’extérieur ?','Uniquement si le modèle et son indice de protection le permettent. Une caméra pour vitre intérieure ne doit pas être assimilée à une caméra extérieure.'],['Le kit comprend-il tous les accessoires ?','L’intitulé de variante et la fiche donnent le contenu documenté. Demandez confirmation pour tout composant non précisé.']],
 guide:'/conseils/dashcam-avant-arriere-guide',guideLabel:'Comprendre le double enregistrement'},
 '/mode-parking': {
 title:'Dashcam mode parking : surveiller une voiture garée | NORTICAM',
 description:'Comparez les dashcams avec mode parking : alimentation, kit compatible, détection et stockage. Préparez votre équipement pour une voiture garée.',
 intro:'Pour une voiture garée, la caméra doit pouvoir rester alimentée et disposer d’un mode adapté. Le mode parking peut fonctionner par détection, intervalles ou selon une autre logique propre au modèle. Choisissez la caméra et son alimentation ensemble : une fonction annoncée ne signifie pas que le kit nécessaire est inclus.',
 criteria:[['La bonne alimentation','Une alimentation permanente compatible ou une solution dédiée peut être nécessaire. Vérifiez les protections prévues et faites installer le kit si besoin.'],['Comprendre ce qui déclenche une séquence','Détection de choc, mouvement et time-lapse ne rendent pas le même service. Consultez la documentation du modèle pour connaître son fonctionnement exact.'],['Autonomie et durée','La durée dépend de l’alimentation, des réglages et de l’environnement. Une mention 24 h ou 48 h ne garantit pas cette durée dans toutes les situations.']],
 faq:[['Le mode parking fonctionne-t-il sur l’allume-cigare ?','Il dépend du maintien de l’alimentation à l’arrêt et des exigences de la caméra. Ne supposez pas que toutes les prises restent actives.'],['La voiture est-elle surveillée sans limite de durée ?','Non. L’énergie disponible et les réglages limitent la durée ; vérifiez la protection contre une décharge excessive.'],['Le kit parking est-il fourni ?','Consultez la variante : plusieurs modèles nécessitent un kit compatible vendu séparément.']],
 guide:'/conseils/dashcam-mode-parking-guide',guideLabel:'Équiper une voiture garée'},
 '/dashcam-vision-nocturne': {
 title:'Dashcam vision nocturne : choisir pour les trajets de nuit | NORTICAM',
 description:'Comparez les dashcams pour la nuit : capteur, HDR, traitement de l’image et alimentation. Trouvez la configuration adaptée à vos trajets.',
 intro:'Pour rouler de nuit, regardez au-delà de la définition. Le capteur et le traitement d’image influencent la scène enregistrée lorsque l’éclairage change. La sélection rassemble les modèles dont le catalogue décrit un traitement nocturne ou HDR ; elle ne constitue pas un classement fondé sur des essais comparatifs.',
 criteria:[['Lumière et mouvement','Une image à l’arrêt dans une rue éclairée ne reflète pas nécessairement un croisement rapide sur une route sombre. Cherchez des séquences représentatives de vos trajets.'],['Comprendre le HDR','Le HDR cherche à mieux gérer les écarts de luminosité. Il ne garantit pas la lecture d’une plaque en toute situation.'],['Préserver la qualité réelle','Un pare-brise propre, un bon positionnement et la maîtrise des reflets comptent aussi. Suivez les réglages conseillés pour le modèle.']],
 faq:[['Vision nocturne signifie-t-elle infrarouge ?','Non. Le terme peut désigner un capteur ou un traitement d’image. La présence d’infrarouge doit être explicitement indiquée.'],['Peut-on identifier toutes les plaques la nuit ?','Non. Le mouvement, la distance, les phares et la météo peuvent empêcher leur lecture.'],['La 4K suffit-elle pour choisir ?','Non. Comparez les informations sur le capteur, le HDR et les conditions des vidéos de démonstration quand elles existent.']],
 guide:'/conseils/dashcam-nuit',guideLabel:'Les critères utiles pour filmer la nuit'},
 '/dashcam-gps': {
 title:'Dashcam GPS : comparer localisation et vidéo | NORTICAM',
 description:'Découvrez les dashcams dont le catalogue mentionne le GPS. Comparez couverture, résolution, variantes et fonctions avant votre achat.',
 intro:'Sur une dashcam, le GPS peut compléter la vidéo par des informations de position ou de vitesse. Il ne faut pas le confondre avec une connexion mobile ou un suivi à distance. Vérifiez si le GPS est intégré, optionnel ou dépendant de la variante avant de choisir.',
 criteria:[['Intégré ou selon variante','Une même famille de produits peut proposer plusieurs équipements. Lisez la description précise du GPS dans la fiche.'],['Consultation des données','Vérifiez comment les données sont affichées ou exportées dans l’application du fabricant. Les possibilités varient selon le modèle.'],['Rester centré sur la caméra','Le GPS ne remplace ni une bonne couverture vidéo ni une installation adaptée. Comparez aussi la définition et l’alimentation.']],
 faq:[['Le GPS permet-il de retrouver une voiture à distance ?','Pas à lui seul. Il faut une fonction de communication et un service compatibles explicitement proposés.'],['GPS et Wi-Fi sont-ils équivalents ?','Non. Le GPS sert à la localisation ; le Wi-Fi relie généralement la caméra au téléphone à proximité.'],['Tous les kits du modèle comprennent-ils le GPS ?','Pas nécessairement. Vérifiez la configuration choisie et demandez confirmation si la fiche indique “selon variante”.']],
 guide:'/conseils/quelle-dashcam-voiture-choisir',guideLabel:'Choisir les fonctions vraiment utiles'},
 '/meilleure-dashcam': {
 title:'Meilleure dashcam 2026 : notre sélection par usage | NORTICAM',
 description:'Quelle dashcam choisir en 2026 ? Comparez la sélection NORTICAM selon votre budget, la couverture, la nuit et le mode parking, sans classement artificiel.',
 intro:'La meilleure dashcam est celle qui correspond à votre véhicule et à vos priorités. Notre sélection 2026 organise les modèles du catalogue par usage, avec leurs prix actuels et les points à vérifier. Il s’agit d’une aide au choix éditoriale, pas d’un palmarès de tests en laboratoire ni d’un classement de ventes.',
 criteria:[['Petit budget ou équipement complet','Comparez le coût du modèle et celui des éléments indispensables, notamment la carte mémoire et l’alimentation parking.'],['Choisir un critère principal','Pour plus de contexte : avant et arrière. Pour examiner le détail : définition et capteur. Pour la voiture garée : mode parking et alimentation.'],['Vérifier les compromis','Un écran, une caméra supplémentaire ou une fonction connectée peut modifier l’encombrement et l’installation. Choisissez ce que vous utiliserez réellement.']],
 faq:[['Existe-t-il une meilleure dashcam pour tout le monde ?','Non. Le véhicule, le budget, l’installation et les angles à filmer changent le choix pertinent.'],['Ce classement est-il basé sur des avis clients ?','Non. Cette sélection s’appuie sur les caractéristiques du catalogue. Aucun avis ni volume de ventes n’est utilisé sans données vérifiables.'],['Comment départager deux modèles ?','Ouvrez le comparateur pour lire les différences, puis vérifiez la variante et le contenu du kit sur chaque fiche.']],
 guide:'/quiz',guideLabel:'Obtenir une recommandation personnalisée'},
};
