import type { Product } from './store-data';
export type Review = { id:string; author:string; rating:number; date:string; title:string; body:string; verified:boolean; images?:string[] };
const names=['Camille R.','Julien M.','Sophie D.','Thomas B.','Léa G.','Antoine C.','Manon P.','Nicolas F.','Élodie V.','Maxime L.','Clara S.','Hugo N.','Sarah K.','Pierre A.','Emma T.','Lucas R.','Inès M.','Romain J.','Chloé B.','Adrien P.'];
const titles=['Très simple à prendre en main','Bonne surprise','Correspond à ce que je cherchais','Installation réfléchie','Image nette sur mes trajets','Pratique au quotidien','Finition soignée','Configuration claire','Rassurant sur la route','Application utile','Bon choix pour mon usage','Je recommande ce modèle','À vérifier selon son véhicule','Fonctions bien expliquées','S’intègre facilement'];
const openings=['Après plusieurs trajets,','Je l’utilise depuis quelques semaines et','Le montage a demandé un peu de préparation, mais','Je cherchais surtout une solution discrète et','J’ai comparé plusieurs configurations avant de choisir :','Reçu et installé pour mes trajets réguliers,','La prise en main est rapide :','Le produit est conforme aux informations de la fiche et','Pour un premier équipement,','Sur route comme en ville,'];
const closings=[' les informations importantes sont faciles à retrouver.',' le résultat correspond bien à mon usage.',' je conseille de vérifier les accessoires avant de commander.',' cela répond au besoin que j’avais identifié.',' la configuration choisie est cohérente avec mon véhicule.',' l’application aide à consulter une séquence sans retirer la carte.',' je suis satisfait(e) de ce choix.',' le format reste discret une fois en place.'];
function seed(value:string){return Array.from(value).reduce((n,c)=>((n*31)+c.charCodeAt(0))>>>0,7);}
export function makeMockReviews(product: Product): Review[] {
 const base=seed(product.handle); const now=new Date('2026-09-10T12:00:00Z');
 return Array.from({length:100},(_,index)=>{const r=(base+index*17)%100; const rating=index<86?5:index<97?4:index<99?3:2;const days=4+((base+index*29)%480);const date=new Date(now);date.setUTCDate(date.getUTCDate()-days);const author=names[(base+index*7)%names.length];const feature=product.details[(base+index*3)%product.details.length] || product.shortTitle;const body=`${openings[(base+index)%openings.length]} ${feature}.${closings[(r+index)%closings.length]}`;return {id:`preview-${product.handle}-${index+1}`,author,rating,date:date.toISOString(),title:titles[(base+index*5)%titles.length],body,verified:index%9!==0};});
}
