// Intentions distinctes des catégories : comprendre le câblage et préparer un montage discret.
export const searchGuides = {
  'dashcam-sans-fil': {
    title: 'Dashcam sans fil : Wi-Fi, batterie et câbles expliqués',
    description: 'Une dashcam Wi-Fi fonctionne-t-elle sans câble ? Comprenez alimentation, batterie, caméra arrière et mode parking pour choisir sans mauvaise surprise.',
    category: 'Comprendre avant d’acheter',
    intro: 'Vous cherchez une dashcam sans fil pour éviter les câbles dans la voiture ? Commencez par distinguer la connexion au téléphone de l’alimentation. Une caméra Wi-Fi peut transférer ses vidéos sans câble tout en restant branchée pour enregistrer. Voici comment choisir une installation qui répond vraiment à votre besoin.',
    sections: [
      ['Le Wi-Fi sert à consulter les vidéos, pas à alimenter la caméra', 'Sur une dashcam compatible, le téléphone se connecte au réseau Wi-Fi de la caméra pour accéder aux réglages ou récupérer des séquences avec l’application du fabricant. Cette liaison ne remplace pas le câble électrique. Elle n’implique pas non plus un accès à distance depuis chez vous. Pour cet usage, il faut une solution explicitement compatible avec une connexion mobile, avec les accessoires et éventuels services requis. Avant achat, séparez donc trois questions : comment la caméra reçoit son énergie, comment vous récupérez les vidéos et si vous avez besoin d’un accès à distance.'],
      ['Sans câble apparent : un objectif différent de « sans branchement »', 'Pour une caméra qui reste dans le véhicule, un montage discret est souvent plus utile qu’une promesse de fonctionnement sans fil. Positionnez le boîtier dans une zone autorisée qui ne gêne pas la visibilité, puis faites cheminer l’alimentation proprement. Le câble ne doit ni traverser le champ de vision ni entraver les airbags ou les commandes. Une alimentation sur prise et un raccordement permanent n’offrent pas les mêmes usages. Si vous envisagez un branchement sur le circuit électrique, faites vérifier la compatibilité et confiez l’intervention à une personne compétente.'],
      ['Batterie intégrée : vérifier son rôle exact', 'La présence d’une batterie ne prouve pas qu’une dashcam peut filmer des heures sans être branchée. Son rôle et son autonomie dépendent du modèle ; certains équipements doivent rester alimentés pour enregistrer normalement. Ne déduisez donc pas l’autonomie du seul mot « batterie » dans une fiche. Une caméra de casque rechargeable répond à un autre usage : elle accompagne le motard et doit être rechargée selon sa notice. Pour une voiture, demandez la durée réelle annoncée en enregistrement, les conditions de mesure et les limites de température avant de choisir une solution autonome.'],
      ['Avant et arrière : faut-il encore un câble ?', 'Une connexion Wi-Fi au téléphone ne signifie pas que la caméra arrière communique sans fil avec la caméra avant. Vérifiez le raccordement prévu pour le kit précis que vous commandez. Le trajet jusqu’à la lunette arrière, la longueur de câble et le passage au niveau du hayon peuvent influencer le choix. Pour comparer deux kits, regardez la définition de chaque caméra, le contenu de la variante et les contraintes de montage. Une résolution 4K annoncée pour l’avant ne s’applique pas automatiquement à l’arrière.'],
      ['Stationnement : prévoir l’énergie avant de choisir la fonction', 'Si votre prise ne fournit plus de courant après l’arrêt du véhicule, elle ne permettra pas à elle seule de maintenir l’enregistrement. Un mode parking peut demander une alimentation compatible et un paramétrage particulier. Vérifiez également la protection contre la décharge de la batterie du véhicule. Un accessoire prévu pour une autre référence n’est pas nécessairement compatible. La durée de surveillance dépend de la consommation et de l’énergie disponible : une mention « mode parking » ne constitue pas une garantie d’enregistrement permanent.'],
      ['Quelle solution choisir selon votre objectif ?', 'Pour récupérer facilement une vidéo après un trajet, privilégiez une dashcam avec application et Wi-Fi documentés. Pour un habitacle épuré, comparez les formats compacts et préparez le cheminement de l’alimentation. Pour enregistrer devant et derrière, choisissez un kit double caméra dont le câblage convient à votre véhicule. Pour surveiller une voiture garée, vérifiez d’abord les conditions du mode parking. Les fiches NORTICAM indiquent les fonctions documentées ; choisissez ensuite la variante et les accessoires nécessaires, sans supposer qu’ils sont tous inclus.'],
      ['Questions fréquentes', 'Faut-il un abonnement pour le Wi-Fi local ? Une connexion directe entre caméra et téléphone n’est pas une connexion mobile ; vérifiez séparément les services proposés par l’application. Peut-on installer sans toucher aux fusibles ? Une alimentation compatible sur prise peut convenir à l’enregistrement en roulant, selon le véhicule. Le Wi-Fi permet-il de voir ma voiture depuis n’importe où ? Pas à lui seul. Existe-t-il une caméra vraiment sans câble ? Certains appareils rechargeables existent, mais leur autonomie et leur usage doivent être confirmés modèle par modèle.'],
    ],
    checklist: ['Distinguer Wi-Fi, alimentation et accès à distance.', 'Vérifier le rôle de la batterie, pas seulement sa présence.', 'Confirmer le raccordement de la caméra arrière.', 'Prévoir l’alimentation du mode parking si nécessaire.'],
    cta: '/dashcam-voiture/', ctaLabel: 'Comparer les dashcams voiture',
  },
  'dashcam-voiture-discrete': {
    title: 'Dashcam discrète : choisir le format et préparer le montage',
    description: 'Mini dashcam ou modèle avec écran ? Comparez encombrement, application, fixation et câblage pour équiper votre voiture sans gêner la visibilité.',
    category: 'Installation discrète',
    intro: 'Une dashcam discrète ne se choisit pas seulement sur ses dimensions. Sa fixation, la place disponible autour du rétroviseur et le passage du câble déterminent le résultat dans votre voiture. L’objectif : conserver le contexte de vos trajets sans ajouter un appareil gênant dans votre champ de vision.',
    sections: [
      ['Mini boîtier ou écran : choisir ce que vous utiliserez vraiment', 'Un modèle sans grand écran peut limiter l’encombrement visuel. Il faut alors être à l’aise avec l’application ou la méthode prévue pour consulter les fichiers. Un écran facilite certains réglages directement sur la caméra, mais demande de vérifier la place disponible. Ne choisissez pas uniquement sur une photo de produit : examinez les dimensions avec la fixation, l’orientation du connecteur et l’espace nécessaire pour retirer la carte mémoire. Un boîtier compact mal placé peut être plus gênant qu’un modèle légèrement plus grand correctement installé.'],
      ['L’emplacement se vérifie depuis le siège conducteur', 'Avant de coller une fixation, vérifiez le champ de vision et l’image cadrée par la caméra, véhicule à l’arrêt. Tenez compte de la zone balayée par les essuie-glaces, des capteurs du véhicule et des préconisations de la notice. Le rétroviseur peut masquer une partie du boîtier depuis le siège conducteur, mais cette position ne convient pas automatiquement à toutes les voitures. Évitez toute fixation qui gêne les dispositifs de sécurité ou impose de manipuler l’appareil en conduisant. Faites un essai de cadrage avant de finaliser l’installation.'],
      ['Le câble fait partie de l’installation', 'La discrétion dépend aussi de l’alimentation. Repérez le trajet du câble jusqu’à la prise ou au raccordement compatible, sans créer de boucle pendante. Ne faites pas passer un câble devant un airbag et ne démontez pas une garniture sans connaître les contraintes du véhicule. Pour une double caméra, ajoutez le trajet vers l’arrière et vérifiez les mouvements du hayon. Une installation propre doit rester sûre, ne pas pincer les fils et permettre l’entretien de la caméra. Un professionnel peut vous aider si le montage nécessite un raccordement permanent.'],
      ['Une petite caméra n’oblige pas à négliger les fonctions utiles', 'Comparez d’abord la couverture souhaitée : avant seulement ou avant et arrière. Regardez ensuite la définition, le traitement des contrastes et la méthode de récupération des vidéos. La lisibilité nocturne ne se déduit pas de la taille du boîtier ni du seul nombre de pixels. Pour vos trajets quotidiens, privilégiez une configuration que vous saurez régler, vérifier et utiliser pour exporter une séquence. Si le stationnement est important, contrôlez les conditions d’alimentation du mode parking et le contenu exact du kit avant d’acheter.'],
      ['Trois formats à examiner dans le catalogue', 'La 70mai M310 Plus est une piste pour un format compact 2K. La DDPAI MINI Pro s’adresse à ceux qui privilégient un boîtier mini avec consultation sur téléphone. Si vous souhaitez deux points de vue sans grand écran, examinez la DDPAI N1 Dual. Ce ne sont pas trois choix équivalents : la couverture, le montage et les fonctions documentées diffèrent. Les prix, variantes et disponibilités se vérifient sur leurs fiches. Comparez aussi le besoin d’une carte mémoire ou d’une alimentation complémentaire pour évaluer votre installation complète.'],
      ['Questions fréquentes avant achat', 'Une caméra discrète est-elle invisible de l’extérieur ? Non : le vitrage, la lumière et la position du boîtier peuvent la rendre visible. Peut-on la cacher totalement derrière le rétroviseur ? Cela dépend de la voiture et ne doit pas nuire au cadrage ou à la sécurité. Un modèle sans écran se règle-t-il facilement ? Vérifiez l’application compatible et les opérations possibles sur le boîtier. Faut-il une mini caméra pour la nuit ? La taille n’est pas le critère décisif ; comparez les fonctions documentées et des vidéos réellement représentatives lorsqu’elles sont disponibles.'],
    ],
    checklist: ['Mesurer le boîtier avec sa fixation et ses connecteurs.', 'Contrôler visibilité, cadrage et accès à la carte.', 'Vérifier le passage des câbles sans gêner les airbags.', 'Choisir avant seul ou avant/arrière avant de comparer la taille.'],
    cta: '/dashcam-voiture/', ctaLabel: 'Voir les modèles voiture et leurs formats',
  },
} as const;
