/** Design reference: NORTICAM CRO product page — decision-first layout, visible trust, native checkout path and mobile sticky action. */
import StorefrontLayout from "@/components/StorefrontLayout";
import { SEOHead } from "@/components/SEOHead";
import { ProductCard, ProductVisual } from "@/components/ProductCard";
import { useCart } from "@/contexts/CartContext";
import { dashcams, euro, productByHandle, type Product } from "@/lib/store-data";
import { ArrowLeft, ArrowRight, Check, ChevronDown, CircleHelp, CreditCard, LockKeyhole, PackageCheck, RotateCcw, ShieldCheck, ShoppingBag, Star, Truck } from "lucide-react";
import { Link, useParams } from "wouter";
import { useMemo, useState } from "react";

const reassurance = [
  { icon: LockKeyhole, title: "Paiement sécurisé", copy: "Finalisé sur le checkout Shopify." },
  { icon: Truck, title: "Livraison offerte", copy: "France · suivi disponible." },
  { icon: RotateCcw, title: "Retour sous 14 jours", copy: "Selon les conditions applicables." },
];

function ProductFaq() {
  const entries = [
    ["Comment choisir la bonne variante ?", "Commencez par le niveau de couverture recherché, puis vérifiez la variante disponible et les informations de compatibilité sur la fiche avant de commander."],
    ["Quand vais-je recevoir ma commande ?", "La préparation est généralement annoncée sous 24 à 48 heures. Le suivi et les informations de livraison sont disponibles dans le parcours de commande Shopify."],
    ["Comment se passe le paiement ?", "Après ajout au panier, votre commande est transmise au panier puis au checkout sécurisé Shopify. NORTICAM ne collecte pas les informations bancaires dans cette page."],
    ["Puis-je retourner un produit ?", "Les demandes de retour sont traitées selon les conditions NORTICAM affichées au moment de la commande. La période indiquée est de 14 jours."],
  ];
  return <section className="border-y border-slate-200 bg-white py-14 sm:py-20"><div className="container max-w-5xl"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="eyebrow">Avant de commander</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-[1.02] tracking-[-.05em] text-slate-950">Les réponses utiles, au bon moment.</h2><p className="mt-4 text-sm leading-7 text-slate-500">Une question reste ouverte ? Parcourez d’abord les informations nécessaires à la décision.</p></div><div className="grid gap-3">{entries.map(([question, answer]) => <details key={question} className="group rounded-2xl border border-slate-200 bg-[#f8fafc] px-5 py-4"><summary className="flex cursor-pointer list-none items-center justify-between gap-4 text-sm font-bold text-slate-950">{question}<ChevronDown size={18} className="text-[#1672d8] transition group-open:rotate-180" /></summary><p className="pt-3 text-sm leading-6 text-slate-500">{answer}</p></details>)}</div></div></div></section>;
}

function ProductPage({ product }: { product: Product }) {
  const { add } = useCart();
  const availableVariants = product.variants.filter((variant) => variant.availableForSale);
  const [variantId, setVariantId] = useState(availableVariants[0]?.id || product.variants[0]?.id || "");
  const selected = product.variants.find((variant) => variant.id === variantId) || product.variants[0];
  const related = useMemo(() => dashcams.filter((item) => item.id !== product.id).slice(0, 3), [product.id]);
  const addSelected = () => { if (selected?.availableForSale) add(product, selected); };
  const details = product.details.length ? product.details.slice(0, 4) : ["Produit sélectionné selon son usage", "Prix et variante synchronisés avec Shopify", "Compatibilité à vérifier avant achat"];
  const schema = { "@context": "https://schema.org", "@type": "Product", name: product.title, image: product.image ? [product.image] : undefined, description: product.description, brand: { "@type": "Brand", name: product.vendor }, offers: { "@type": "Offer", url: product.shopifyUrl, priceCurrency: "EUR", price: String(selected?.price ?? product.price), availability: selected?.availableForSale ? "https://schema.org/InStock" : "https://schema.org/OutOfStock" } };
  return <StorefrontLayout><SEOHead title={`${product.title} : prix, variantes et disponibilité | NORTICAM`} description={`${product.title} : consultez la variante disponible, les informations produit et le parcours sécurisé NORTICAM.`} image={product.image} type="product" jsonLd={schema} />
    <section className="bg-[#f7f8f9] pb-24 pt-5 sm:pb-14 sm:pt-9"><div className="container"><Link href="/boutique" className="mb-5 inline-flex items-center gap-1.5 text-sm font-bold text-slate-500 transition hover:text-[#1672d8]"><ArrowLeft size={16} />Retour à la boutique</Link><div className="grid gap-8 lg:grid-cols-[1.06fr_.94fr] lg:gap-14"><div className="lg:sticky lg:top-24 lg:self-start"><div className="relative overflow-hidden rounded-[2rem] bg-[#e8ebed] shadow-[0_15px_35px_rgba(15,23,42,.07)]"><div className="aspect-square"><ProductVisual product={product} priority /></div><span className="absolute left-5 top-5 rounded-full bg-white/95 px-3 py-1.5 text-[10px] font-bold uppercase tracking-[.14em] text-[#1672d8]">{product.badge}</span>{product.image && <div className="absolute bottom-4 left-4 flex gap-2"><span className="grid h-12 w-12 place-items-center overflow-hidden rounded-xl border-2 border-[#1672d8] bg-white"><img src={product.image} alt="Aperçu du produit" className="h-full w-full object-cover" /></span></div>}</div><p className="mt-3 flex items-center gap-2 text-xs text-slate-500"><CircleHelp size={14} className="text-[#1672d8]" />Les visuels sont issus du catalogue produit synchronisé.</p></div>
      <div className="max-w-xl"><p className="eyebrow">{product.vendor} · sélection NORTICAM</p><h1 className="mt-3 font-display text-4xl font-extrabold leading-[.98] tracking-[-.055em] text-slate-950 sm:text-5xl">{product.shortTitle}</h1><p className="mt-5 text-base leading-7 text-slate-600">{product.story}</p><div className="mt-6 inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-2 text-xs font-bold text-[#1265bd]"><ShieldCheck size={15} />Choisi à partir du catalogue actuellement disponible</div>
        <div className="mt-7 flex items-end justify-between border-y border-slate-200 py-5"><div><p className="text-[11px] font-bold uppercase tracking-[.14em] text-slate-400">Prix {product.variants.length > 1 ? "à partir de" : ""}</p><p className="mt-1 font-display text-4xl font-extrabold tracking-tight text-slate-950">{euro(selected?.price ?? product.price)}</p></div><span className={`rounded-full px-3 py-1.5 text-xs font-bold ${selected?.availableForSale ? "bg-emerald-50 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{selected?.availableForSale ? "Disponible" : "Indisponible"}</span></div>
        {product.variants.length > 1 && <label className="mt-6 block text-sm font-bold text-slate-950">Choisir une variante<select value={variantId} onChange={(event) => setVariantId(event.target.value)} className="mt-2 block w-full rounded-xl border border-slate-200 bg-white px-4 py-3 text-sm font-medium outline-none ring-[#1672d8] focus:ring-2">{product.variants.map((variant) => <option key={variant.id} value={variant.id} disabled={!variant.availableForSale}>{variant.title} — {euro(variant.price)}{variant.availableForSale ? "" : " (indisponible)"}</option>)}</select></label>}
        <div className="mt-7 rounded-[1.5rem] bg-white p-5 shadow-[0_8px_24px_rgba(15,23,42,.045)]"><p className="text-[11px] font-bold uppercase tracking-[.14em] text-[#1672d8]">Pourquoi ce modèle mérite votre attention</p><ul className="mt-4 grid gap-3">{details.map((detail) => <li key={detail} className="flex gap-3 text-sm leading-6 text-slate-600"><span className="mt-0.5 grid h-5 w-5 shrink-0 place-items-center rounded-full bg-blue-50 text-[#1672d8]"><Check size={13} /></span><span>{detail}</span></li>)}</ul></div>
        <button onClick={addSelected} disabled={!selected?.availableForSale} className="mt-6 flex h-14 w-full items-center justify-center gap-2 rounded-full bg-[#1672d8] px-6 text-sm font-bold text-white shadow-[0_12px_28px_rgba(22,114,216,.25)] transition hover:bg-[#075dbb] active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-45"><ShoppingBag size={18} />{selected?.availableForSale ? "Ajouter au panier" : "Variante indisponible"}</button>
        <div className="mt-3 grid grid-cols-3 gap-2 text-center text-[10px] font-bold uppercase tracking-[.08em] text-slate-500"><span className="rounded-lg border border-slate-200 bg-white px-2 py-2">CB</span><span className="rounded-lg border border-slate-200 bg-white px-2 py-2">Paiement sécurisé</span><span className="rounded-lg border border-slate-200 bg-white px-2 py-2">Shopify</span></div><p className="mt-3 text-center text-xs leading-5 text-slate-500">Vos informations de paiement sont traitées au checkout sécurisé Shopify.</p>
        <div className="mt-6 grid gap-3 rounded-[1.5rem] bg-slate-950 p-4 text-white sm:grid-cols-3">{reassurance.map(({ icon: Icon, title, copy }) => <div key={title} className="flex gap-2.5"><Icon size={17} className="mt-0.5 shrink-0 text-[#75b8ff]" /><div><p className="text-xs font-bold">{title}</p><p className="mt-1 text-[11px] leading-4 text-slate-300">{copy}</p></div></div>)}</div>
      </div></div></div></section>
    <section className="bg-[#eaf3ff] py-12 sm:py-16"><div className="container"><div className="grid gap-6 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">Votre choix, sans approximation</p><h2 className="mt-3 font-display text-3xl font-extrabold leading-[1.03] tracking-[-.05em] text-slate-950">Vous hésitez encore ? Reprenez par votre usage.</h2><p className="mt-4 text-sm leading-7 text-slate-600">Le diagnostic vous aide à situer ce modèle parmi les options disponibles avant votre achat.</p><Link href="/quiz" className="mt-6 inline-flex items-center gap-2 rounded-full bg-slate-950 px-5 py-3 text-sm font-bold text-white hover:bg-[#1672d8]">Faire le diagnostic <ArrowRight size={16} /></Link></div><div className="rounded-[1.7rem] bg-white p-6 shadow-[0_12px_28px_rgba(15,23,42,.05)]"><div className="flex items-center gap-3"><span className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-50 text-[#1672d8]"><PackageCheck size={21} /></span><div><p className="font-display font-extrabold text-slate-950">Ce qu’il faut contrôler avant commande</p><p className="mt-1 text-sm text-slate-500">La variante, la compatibilité et les accessoires attendus.</p></div></div><div className="mt-6 grid gap-3 sm:grid-cols-3">{["Variante sélectionnée", "Compatibilité véhicule", "Accessoires utiles"].map((item) => <div key={item} className="rounded-xl bg-slate-50 p-3 text-sm font-bold text-slate-700"><CreditCard size={16} className="mb-3 text-[#1672d8]" />{item}</div>)}</div></div></div></div></section>
    <ProductFaq />
    <section className="py-14 sm:py-20"><div className="container"><div className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">Poursuivre votre sélection</p><h2 className="mt-3 font-display text-3xl font-extrabold tracking-[-.05em] text-slate-950">Comparer d’autres modèles.</h2></div><Link href="/comparatif" className="inline-flex items-center gap-1 text-sm font-bold text-[#1672d8]">Ouvrir le comparatif <ArrowRight size={16} /></Link></div><div className="mt-7 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{related.map((item) => <ProductCard key={item.id} product={item} />)}</div></div></section>
    <div className="fixed inset-x-0 bottom-0 z-[60] border-t border-slate-200 bg-white/95 px-4 py-3 shadow-[0_-8px_24px_rgba(15,23,42,.08)] backdrop-blur lg:hidden"><div className="mx-auto flex max-w-lg items-center gap-3"><div className="min-w-0"><p className="truncate text-xs font-bold text-slate-950">{product.shortTitle}</p><p className="font-display text-base font-extrabold">{euro(selected?.price ?? product.price)}</p></div><button onClick={addSelected} disabled={!selected?.availableForSale} className="ml-auto inline-flex h-11 shrink-0 items-center gap-2 rounded-full bg-[#1672d8] px-4 text-xs font-bold text-white disabled:opacity-45"><ShoppingBag size={16} />Ajouter</button></div></div>
  </StorefrontLayout>;
}

export default function ProductConversion() {
  const { handle } = useParams<{ handle: string }>(); const product = productByHandle(handle);
  if (!product) return <StorefrontLayout><SEOHead title="Produit introuvable | NORTICAM" description="Retrouvez nos dashcams voiture et moto disponibles dans la boutique NORTICAM." /><div className="container py-24 text-center"><h1 className="font-display text-4xl font-extrabold">Produit introuvable</h1><Link href="/boutique" className="mt-6 inline-flex rounded-full bg-slate-950 px-5 py-3 text-sm font-bold text-white">Retour à la boutique</Link></div></StorefrontLayout>;
  return <ProductPage product={product} />;
}
